CREATE TABLE Carro
(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Modelo VARCHAR(100) NOT NULL,
    Ano INTEGER NOT NULL,
    Cor VARCHAR(50) NOT NULL,
    Chassi VARCHAR(17) UNIQUE NOT NULL
);

CREATE TABLE Peça
(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Codigo VARCHAR(50) NOT NULL,
    Tipo VARCHAR(50) NOT NULL,
    Fornecedor VARCHAR(100) NOT NULL
);

CREATE TABLE Venda
(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Emissao DATE NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    forma_de_pagamento VARCHAR(50) NOT NULL
);